export const circuitData = {
    "Yas Marina Circuit": "ae-2009.geojson",
    "Red Bull Ring": "at-1969.geojson",
    "Albert Park Circuit": "au-1953.geojson",
    "Baku City Circuit": "az-2016.geojson",
    "Spa Francorchamps": "be-1925.geojson",
    "Bahrain International Circuit": "bh-2002.geojson",
    "Interlagos - Autódromo José Carlos Pace": "br-1940.geojson",
    "Jacarepaguá - Autódromo Internacional Nelson Piquet": "br-1977.geojson",
    "Circuit Gilles-Villeneuve": "ca-1978.geojson",
    "Shanghai International Circuit": "cn-2004.geojson",
    "Nürburgring": "de-1927.geojson",
    "Hockenheimring": "de-1932.geojson",
    "Circuit de Barcelona-Catalunya": "es-1991.geojson",
    "Circuit de Nevers Magny-Cours": "fr-1960.geojson",
    "Circuit Paul Ricard": "fr-1969.geojson",
    "Silverstone Circuit": "gb-1948.geojson",
    "Hungaroring": "hu-1986.geojson",
    "Autodromo Internazionale del Mugello": "it-1914.geojson",
    "Autodromo Nazionale Monza": "it-1922.geojson",
    "Autodromo Enzo e Dino Ferrari": "it-1953.geojson",
    "Suzuka International Racing Course": "jp-1962.geojson",
    "Circuit de Monaco": "mc-1929.geojson",
    "Autódromo Hermanos Rodríguez": "mx-1962.geojson",
    "Sepang International Circuit": "my-1999.geojson",
    "Circuit Zandvoort": "nl-1948.geojson",
    "Autódromo do Estoril": "pt-1972.geojson",
    "Autódromo Internacional do Algarve": "pt-2008.geojson",
    "Losail International Circuit": "qa-2004.geojson",
    "Sochi Autodrom": "ru-2014.geojson",
    "Jeddah Corniche Circuit": "sa-2021.geojson",
    "Marina Bay Street Circuit": "sg-2008.geojson",
    "Intercity Istanbul Park": "tr-2005.geojson",
    "Circuit of the Americas": "us-2012.geojson",
    "Miami International Autodrome": "us-2022.geojson",
    "Las Vegas Street Circuit": "us-2023.geojson"
};
